### PR TITLE
Fix gzip encoding

### PR DESCRIPTION
**Pull request by ComFreek**
Split from originally larger PR #271. See there for discussion.

### CODE REVIEW

**Review by ptersilie — APPROVED** [review]

**Comment by ptersilie** [comment]
Thanks a lot! This is much appreciated. Before we merge, could you rebase it against master and change the commit message to something like "Fix encoding when opening JSON files"?

**Comment by ComFreek** [comment]
Hopefully done now :smile:

**Comment by ptersilie** [comment]
Unfortunately, you just merged master into this branch. In order to make the merge commits to disappear, you will need to rebase this branch against our master, either by doing `git pull --rebase https://github.com/softdevteam/eco` or `git rebase origin/master` (if you've already synced your master branch) .

**Comment by ptersilie** [comment]
Merged manually!

**Pull request closed without merging**
