### PR TITLE
Disable graph view if parser was loaded from cache

### LINKED ISSUE #8: Show Stategraph raises Python exception
This issue report is based on the code given in `TUTORIAL`, which Eco shows to be correctly parsed.

Steps to reproduce:
1. Reproduce the code from `TUTORIAL`
2. Click on **View** in the menu
3. Select **StateGraph** from the drop-down
4. Click on **Show whole graph**

Traceback is:

``` python
$ Traceback (most recent call last):
  File "eco.py", line 265, in showWholeGraph
    self.viewer.create_pydot_graph(editor.tm.get_mainparser().graph)
  File "/home/snim2/Desktop/working/snim2/eco/lib/eco/viewer.py", line 170, in create_pydot_graph
    if isinstance(node, AstNode):
AttributeError: 'NoneType' object has no attribute 'state_sets'
```

### PR DESCRIPTION
**Pull request by ptersilie**
Fixes #8.

### CODE REVIEW

**Comment by ltratt** [comment]
Might this better be `self.ui.actionStateGraph.setEnabled(ed_tab.editor.tm.get_mainparser().graph)`?

**Comment by ptersilie** [comment]
Well graph is not a boolean, so even if it works it feels a bit weird to say `setEnabled(someobject)`.

**Comment by ltratt** [comment]
Fair enough!

**Pull request merged**
