### PR TITLE
Fix selection width on OS X.

### PR DESCRIPTION
**Pull request by jaheba**
See #101.

### CODE REVIEW

**Comment by ptersilie** [comment]
Can you explain again why this works? Is it a bug in Qt (in that case we might want to submit a bug report)? Theoretically `self.fontm.width(" ")` should be the font width of every character in a fixed-width font. How come this is not true for some font sizes?

**Comment by ltratt** [comment]
I _think_ the point is that the width(" ") returns a width in integer points, whereas there's no particular reason a font designer needs to make sure their characters have a width that's an integer number of points. Is that correct?

**Comment by ptersilie** [comment]
Ah, that actually does make sense. Although even when we tried using the same font (Monospace) on both my and @jaheba's machine, it didn't work on his mac. Unless macos does something weird to all its fonts.

**Comment by ptersilie** [comment]
Then again, I think `width()` returns the size of a string in pixels how they are rendered by Qt. I'm not sure how anything can be 1.275 pixels wide.

**Comment by ltratt** [comment]
I think my comment still stands, even if the width is in pixels. There's no reason a character width needs to precisely align with pixels. [For an extreme example, imagine we rendered fonts at 2pt -- the pixels are much bigger than many of the font's strokes.]

**Comment by jaheba** [comment]
I quote myself here:

> The underlying problem is that the font size is measured in points and thus is in relation to inches. So setting the font size from 15 to 16 may result in the same width for a single character, say 10. The width of 100 characters however is quite different, in my case 963 and 1068.

**Comment by ptersilie** [comment]
It was that quote I had issues with. ;) Especially

> font size is measured in points and thus is in relation to inches.

**Comment by jaheba** [comment]
72pts is 1inch. It refers to the actual size displayed. It has nothing to do with mac doing something weird, but simple maths. As you said correctly nothing can be `1.275px` wide. So Qt has to approximate to the nearest pixel, which would be `1px` in this case. But if you have longer text Qt can render those pixels better to fit their actual size, with the result that a 100 character text may take 128px.

**Comment by ptersilie** [comment]
Ah I get it now. If my text is `abc` and the font would render that at 25px, then this would make each character 8.33 pixels wide. Conversion to int makes this 8px for each character which is why the cursor (which is drawn using font.width \* x-coordinate) is off.

I'm still wondering why this only seems to be an issue on Mac and not Linux even when using the same fonts. But I'm happy with this explanation now.

**Comment by ltratt** [comment]
Yes, I _think_ that's what's going on too.

**Comment by snim2** [comment]
Possibly silly question, but @jaheba which version of Python are you using to run Eco?

**Comment by ltratt** [comment]
@ptersilie It's possible that width(" ") returns floats on Linux / OpenBSD? I'm not sure this is hugely likely, but it may explain why neither you or I seem able to replicate this problem. It may also be that the fonts we choose to use are designed to have "perfect" widths (if that makes sense).

**Comment by jaheba** [comment]
```
$ python --version
Python 2.7.10
```

**Comment by jaheba** [comment]
Maybe the aliasing algorithm behaves different?

https://en.wikipedia.org/wiki/Font_rasterization

> Mac OS X's Quartz is distinguished by the use of floating-point positioning[citation needed]; it does not force glyphs into exact pixel locations, instead using various antialiasing techniques, including subpixel rendering, to position characters and lines to appear closer to the type designer's intent.

**Comment by ptersilie** [comment]
@ltratt We tried using the same fonts tho (Monospace). So unless they are different on Mac, it doesn't seem the fonts being the problem.

**Comment by ltratt** [comment]
It's possible.

Anyway, assuming this PR doesn't break things on Linux, I think it's worth merging.

**Comment by ptersilie** [comment]
Of course. I'll run a few more checks and then merge it.

**Pull request merged**
