### PR TITLE
Added little arrows to indicate empty language boxes

### PR DESCRIPTION
**Pull request by ptersilie**
Added arrows that indicate where empty language boxes are, to fix issue #130

### CODE REVIEW

**Comment by ptersilie** [comment]
Don't merge this just yet. I will fix the "double click on the parsing status" bug first.

**Comment by ptersilie** [comment]
Ready to merge.

**Comment by ltratt** [comment]
I think we should assign @djmcalleja to do a code review (under Sarah's guidance) and then do the merge.

**Comment by ptersilie** [comment]
Sure. I was going to assign him, although would have been happy with him just testing the changes. But a code review is probably a valuable lesson.

Edit: Assigned both @snim2 and @djmcalleja

**Comment by ltratt** [comment]
[NB: This will require squashing before the merge, I think.]

**Comment by ltratt** [comment]
Oooo, assigning multiple people is new, I think. Very useful!

**Comment by ptersilie** [comment]
@ltratt  not necessarily, as one is an improvement and the other a bug fix. But as a squashing exercise for @djmcalleja I wouldn't mind having this squashed. If it is squashed however, please merge the two commit messages, so I know that this fixes two different things.

I recommend as a squashed commit message:

```
Improved finding empty language boxes

Added little arrows into the editor to indicate the position of empty (and otherwise invisible) language boxes. This also fixes the doubleclicking on the parsing status to jump to errors and inside language boxes. 
```

**Comment by djmcalleja** [comment]
What do I have to do for the code review and what is squashing?

**Comment by snim2** [comment]
@djmcalleja Are you on MatterMost at the moment? I will talk you through the process there...

**Comment by ltratt** [comment]
@ptersilie OK, I see. Let's not squash it if it doesn't need it.

**Comment by ptersilie** [comment]
@ltratt I don't mind, I added a sensible commit message for the squash (see above) in case you want to squash

**Comment by djmcalleja** [comment]
Tested and reviewed the code and it looks good! I will now click the "merge pull request" button.

**Comment by ptersilie** [comment]
:+1:

**Pull request merged**
