### PR TITLE
Import bug

### PR DESCRIPTION
**Pull request by ptersilie**
Some fixes related to saving and loading Eco files

### CODE REVIEW

**Comment by ltratt** [comment]
If I load `range.eco`, it does load but as soon as I try and edit a character I get:
```python
Traceback (most recent call last):
  File "/home/ltratt/src/eco/lib/eco/nodeeditor.py", line 857, in keyPressEvent
    self.tm.key_normal(text)
  File "/home/ltratt/src/eco/lib/eco/treemanager.py", line 1041, in key_normal
    self.reparse(node, need_reparse)
  File "/home/ltratt/src/eco/lib/eco/treemanager.py", line 1865, in reparse
    parser.inc_parse()
  File "/home/ltratt/src/eco/lib/eco/incparser/incparser.py", line 259, in inc_parse
    self.reduce(element)
  File "/home/ltratt/src/eco/lib/eco/incparser/incparser.py", line 628, in reduce
    self.interpret_annotation(new_node, element.action)
  File "/home/ltratt/src/eco/lib/eco/incparser/incparser.py", line 647, in interpret_annotation
    astnode = annotation.interpret(node)
  File "/home/ltratt/src/eco/lib/eco/grammar_parser/bootstrap.py", line 597, in interpret
    assert isinstance(expr1, ListNode)
AssertionError
```

**Comment by ltratt** [comment]
[`rng3.eco` seems fine BTW.]

**Comment by ltratt** [comment]
Should we merge this PR and fix the `range.eco` bug separately or ...?

**Comment by ptersilie** [comment]
Nah I think I should fix that as well in here. This has to do with the AST that is apparently not properly initialised after loading a file. Since the other commits also fix stuff with file loading I think it would fit in here.

**Comment by ltratt** [comment]
OK, sounds good to me. I won't merge yet :)

**Comment by ptersilie** [comment]
I have reason to believe that that error only occurs because you have an outdated Eco file (i.e. the grammar has changed) which first results in an error and then on a reparse tries to reuse parse trees that are not valid anymore because the grammar has changed.

If you fix the file this shouldn't happen anymore, even if you save the file with parsing errors, as long as the parsing errors happened with the same grammar.

**Comment by ptersilie** [comment]
I squashed. I think we can merge this. Let me know if you spot any more errors related to this.

**Comment by ltratt** [comment]
@lukasd I think you're right. I've recreated range.eco from scratch, and the new version loads back in correctly.

**Comment by ltratt** [comment]
OK, do we want to squash this before I merge?

**Comment by ptersilie** [comment]
I think it's fine as it is.

**Pull request merged**
