### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by ptersilie**
This PR contains various improvements for Eco which are as follows:

- 091cce4: Refactors grammars.py.
- 8ed0d48: Allows us to run parts of Eco using PyPy.
- 920ec09: Fixes a bug with the indentation when importing files with an empty first line.
- 44f7249: Allows us to quickly jump to errors within the editor.
- 3818ea6: Added an option to restrict automatic language boxes to new tokens.
- aedc9fd: Fixes automatic language boxes to in certain scenarios.
- ee2a13c: Use production order to resolve reduce/reduce conflicts.

### CODE REVIEW

**Comment by ltratt** [comment]
A few comments. Let's address the code ones first, get that sorted out, then we can do the commit message fixing as a second step.

**Comment by ptersilie** [comment]
I have removed that one outdated comment. Since the Production thingy is not so easily fixed, I suggest we just leave it. Since reduce/reduce conflicts are rather rare, there shouldn't be any penalty from the dict lookups.

If you are happy with this, then I'll do the commit messages next.

**Comment by ltratt** [comment]
OK, please do the commit messages.

**Comment by ptersilie** [comment]
Reworded the commit messages and squashed the latest commit.

**Review by ltratt — APPROVED** [review]

**Comment by ltratt** [comment]
Something has gone wrone with Travis I think? I've tried kicking it...

**Pull request merged**
