### PR TITLE
Fix CHARACTER_LITERAL in Java grammar

### PR DESCRIPTION
**Pull request by ptersilie**
This updates the lexing rule for character literals in Java according to spec. Allowed between single quotes are:

- any printable character other than a backslash or '
- Escaped characters: `\b \t \n \f \r \" \' \\`
- Escaped octal number between 000 and 377 (e.g. `\123`)
- Esacped Unicode, e.g. `\u012A`

To view the diff of these changes use `./bin/diffeco lib/eco/grammars/java15.eco -c master`.

### CODE REVIEW

**Comment by ltratt** [comment]
Do we need to make an update to https://github.com/softdevteam/grammars/blob/master/java7/java.l too based on this?

**Comment by ptersilie** [comment]
I would think so. Remind me what `?:\\\\` does again?

**Comment by ltratt** [comment]
We use https://docs.rs/regex/1.1.6/regex/ syntax in that repo.

**Comment by ltratt** [comment]
So `(?:\\\\|blah)` means "match `\\` or `blah` but don't make a group for that".

**Comment by ptersilie** [comment]
I see. Should I update that repo as well or do you want to do that?

**Comment by ltratt** [comment]
I will happily accept a PR to the grammars repo :)

**Comment by ltratt** [comment]
Is this ready for squashing?

**Comment by ptersilie** [comment]
Squashed!

**Review by ltratt — APPROVED** [review]

**Pull request merged**
