### PR TITLE
Fixed undo bug (issue #136)

### LINKED ISSUE #136: Error found by randomised testing
``` bash
=============================================== test session starts ===============================================
platform linux2 -- Python 2.7.11 -- py-1.4.31 -- pytest-2.7.1
rootdir: /home/snim2/Desktop/working/softdev/eco/lib/eco/test, inifile: 
plugins: hypothesis, xdist, cov
collected 121 items 

test/test_eco.py ..........ssssssss...................................................................................F...................

==================================================== FAILURES =====================================================
___________________________________ Test_Undo.test_undo_random_insertdeleteundo ___________________________________

self = <test.test_eco.Test_Undo instance at 0x7f20034b7a70>

    def test_undo_random_insertdeleteundo(self):
>       self.random_insert_delete_undo(programs.pythonsmall)

test/test_eco.py:2138: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/test_eco.py:2228: in random_insert_delete_undo
    self.text_compare(program)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test.test_eco.Test_Undo instance at 0x7f20034b7a70>
original = ['class X:', '    def helloworld(x, y, z):', '        for x in range(0, 10):', '            if x == 1:', '                return 1', '            else:', ...]

    def text_compare(self, original):
        original = original.replace("\r", "").split("\n")
        current = self.treemanager.export_as_text("/dev/null").replace("\r", "").split("\n")

        for i in xrange(len(current)):
>           assert original[i] == current[i]
E           assert '        y = 2' == '&e ( { !     y = 2'
E             -         y = 2
E             + &e ( { !     y = 2

test/test_eco.py:1620: AssertionError
---------------------------------------------- Captured stdout call -----------------------------------------------
self.treemanager.cursor_reset()
self.move(DOWN, 1)
self.move(RIGHT, 0)
self.treemanager.key_normal(' ')
self.treemanager.cursor_reset()
self.move(DOWN, 1)
self.move(RIGHT, 3)
self.treemanager.key_delete()
self.treemanager.cursor_reset()
self.move(DOWN, 1)
self.move(RIGHT, 2)
self.treemanager.key_normal('y')
self.treemanager.cursor_reset()
self.move(DOWN, 1)
self.move(RIGHT, 4)
self.treemanager.key_normal('*')
self.treemanager.cursor_reset()
self.move(DOWN, 1)
self.move(RIGHT, 1)
self.treemanager.key_normal('0')
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 2)
self.move(RIGHT, 3)
self.treemanager.key_normal('a')
self.treemanager.cursor_reset()
self.move(DOWN, 2)
self.move(RIGHT, 4)
self.treemanager.key_ctrl_z()
self.treemanager.cursor_reset()
self.move(DOWN, 2)
self.move(RIGHT, 2)
self.treemanager.key_ctrl_z()
self.treemanager.cursor_reset()
self.move(DOWN, 2)
self.move(RIGHT, 1)
self.treemanager.key_normal('k')
self.treemanager.cursor_reset()
self.move(DOWN, 2)
self.move(RIGHT, 0)
self.treemanager.key_normal('t')
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 13)
self.move(RIGHT, 1)
self.treemanager.key_normal('k')
self.treemanager.cursor_reset()
self.move(DOWN, 13)
self.move(RIGHT, 2)
self.treemanager.key_normal('&')
self.treemanager.cursor_reset()
self.move(DOWN, 13)
self.move(RIGHT, 0)
self.treemanager.key_normal('u')
self.treemanager.cursor_reset()
self.move(DOWN, 13)
self.move(RIGHT, 4)
self.treemanager.key_normal('\r')
self.treemanager.cursor_reset()
self.move(DOWN, 13)
self.move(RIGHT, 3)
self.treemanager.key_normal('w')
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 4)
self.move(RIGHT, 1)
self.treemanager.key_normal('*')
self.treemanager.cursor_reset()
self.move(DOWN, 4)
self.move(RIGHT, 2)
self.treemanager.key_delete()
self.treemanager.cursor_reset()
self.move(DOWN, 4)
self.move(RIGHT, 4)
self.treemanager.key_normal('!')
self.treemanager.cursor_reset()
self.move(DOWN, 4)
self.move(RIGHT, 3)
self.treemanager.key_normal('9')
self.treemanager.cursor_reset()
self.move(DOWN, 4)
self.move(RIGHT, 0)
self.treemanager.key_normal('x')
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 12)
self.move(RIGHT, 4)
self.treemanager.key_delete()
self.treemanager.cursor_reset()
self.move(DOWN, 12)
self.move(RIGHT, 1)
self.treemanager.key_normal('q')
self.treemanager.cursor_reset()
self.move(DOWN, 12)
self.move(RIGHT, 0)
self.treemanager.key_normal(':')
self.treemanager.cursor_reset()
self.move(DOWN, 12)
self.move(RIGHT, 2)
self.treemanager.key_delete()
self.treemanager.cursor_reset()
self.move(DOWN, 12)
self.move(RIGHT, 3)
self.treemanager.key_normal('l')
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 0)
self.move(RIGHT, 2)
self.treemanager.key_normal('q')
self.treemanager.cursor_reset()
self.move(DOWN, 0)
self.move(RIGHT, 3)
self.treemanager.key_normal('d')
self.treemanager.cursor_reset()
self.move(DOWN, 0)
self.move(RIGHT, 4)
self.treemanager.key_normal('z')
self.treemanager.cursor_reset()
self.move(DOWN, 0)
self.move(RIGHT, 1)
self.treemanager.key_normal(')')
self.treemanager.cursor_reset()
self.move(DOWN, 0)
self.move(RIGHT, 0)
self.treemanager.key_delete()
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 10)
self.move(RIGHT, 2)
self.treemanager.key_normal('y')
self.treemanager.cursor_reset()
self.move(DOWN, 10)
self.move(RIGHT, 4)
self.treemanager.key_normal('q')
self.treemanager.cursor_reset()
self.move(DOWN, 10)
self.move(RIGHT, 0)
self.treemanager.key_delete()
self.treemanager.cursor_reset()
self.move(DOWN, 10)
self.move(RIGHT, 3)
self.treemanager.key_normal('+')
self.treemanager.cursor_reset()
self.move(DOWN, 10)
self.move(RIGHT, 1)
self.treemanager.key_normal('!')
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 3)
self.move(RIGHT, 2)
self.treemanager.key_normal('5')
self.treemanager.cursor_reset()
self.move(DOWN, 3)
self.move(RIGHT, 0)
self.treemanager.key_normal('+')
self.treemanager.cursor_reset()
self.move(DOWN, 3)
self.move(RIGHT, 4)
self.treemanager.key_normal('+')
self.treemanager.cursor_reset()
self.move(DOWN, 3)
self.move(RIGHT, 1)
self.treemanager.key_normal('v')
self.treemanager.cursor_reset()
self.move(DOWN, 3)
self.move(RIGHT, 3)
self.treemanager.key_normal('=')
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 7)
self.move(RIGHT, 3)
self.treemanager.key_delete()
self.treemanager.cursor_reset()
self.move(DOWN, 7)
self.move(RIGHT, 2)
self.treemanager.key_ctrl_z()
self.treemanager.cursor_reset()
self.move(DOWN, 7)
self.move(RIGHT, 0)
self.treemanager.key_normal('g')
self.treemanager.cursor_reset()
self.move(DOWN, 7)
self.move(RIGHT, 4)
self.treemanager.key_delete()
self.treemanager.cursor_reset()
self.move(DOWN, 7)
self.move(RIGHT, 1)
self.treemanager.key_delete()
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 5)
self.move(RIGHT, 0)
self.treemanager.key_ctrl_z()
self.treemanager.cursor_reset()
self.move(DOWN, 5)
self.move(RIGHT, 3)
self.treemanager.key_delete()
self.treemanager.cursor_reset()
self.move(DOWN, 5)
self.move(RIGHT, 4)
self.treemanager.key_normal('0')
self.treemanager.cursor_reset()
self.move(DOWN, 5)
self.move(RIGHT, 2)
self.treemanager.key_normal(')')
self.treemanager.cursor_reset()
self.move(DOWN, 5)
self.move(RIGHT, 1)
self.treemanager.key_delete()
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 6)
self.move(RIGHT, 0)
self.treemanager.key_normal('%')
self.treemanager.cursor_reset()
self.move(DOWN, 6)
self.move(RIGHT, 4)
self.treemanager.key_delete()
self.treemanager.cursor_reset()
self.move(DOWN, 6)
self.move(RIGHT, 3)
self.treemanager.key_normal('c')
self.treemanager.cursor_reset()
self.move(DOWN, 6)
self.move(RIGHT, 1)
self.treemanager.key_normal('9')
self.treemanager.cursor_reset()
self.move(DOWN, 6)
self.move(RIGHT, 2)
self.treemanager.key_delete()
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 8)
self.move(RIGHT, 1)
self.treemanager.key_normal(']')
self.treemanager.cursor_reset()
self.move(DOWN, 8)
self.move(RIGHT, 3)
self.treemanager.key_normal('{')
self.treemanager.cursor_reset()
self.move(DOWN, 8)
self.move(RIGHT, 4)
self.treemanager.key_normal('l')
self.treemanager.cursor_reset()
self.move(DOWN, 8)
self.move(RIGHT, 0)
self.treemanager.key_normal('c')
self.treemanager.cursor_reset()
self.move(DOWN, 8)
self.move(RIGHT, 2)
self.treemanager.key_delete()
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 9)
self.move(RIGHT, 0)
self.treemanager.key_delete()
self.treemanager.cursor_reset()
self.move(DOWN, 9)
self.move(RIGHT, 3)
self.treemanager.key_normal('f')
self.treemanager.cursor_reset()
self.move(DOWN, 9)
self.move(RIGHT, 1)
self.treemanager.key_normal('h')
self.treemanager.cursor_reset()
self.move(DOWN, 9)
self.move(RIGHT, 2)
self.treemanager.key_normal('1')
self.treemanager.cursor_reset()
self.move(DOWN, 9)
self.move(RIGHT, 4)
self.treemanager.key_normal('v')
self.treemanager.undo_snapshot()
self.treemanager.cursor_reset()
self.move(DOWN, 11)
self.move(RIGHT, 0)
self.treemanager.key_normal('&')
self.treemanager.cursor_reset()
self.move(DOWN, 11)
self.move(RIGHT, 4)
self.treemanager.key_normal('!')
self.treemanager.cursor_reset()
self.move(DOWN, 11)
self.move(RIGHT, 3)
self.treemanager.key_normal('{')
self.treemanager.cursor_reset()
self.move(DOWN, 11)
self.move(RIGHT, 2)
self.treemanager.key_normal('(')
self.treemanager.cursor_reset()
self.move(DOWN, 11)
self.move(RIGHT, 1)
self.treemanager.key_normal('e')
self.treemanager.undo_snapshot()
================================ 1 failed, 112 passed, 8 skipped in 146.04 seconds ================================
$ 
```

### PR DESCRIPTION
**Pull request by ptersilie**
Fixes #136

### CODE REVIEW

**Comment by snim2** [comment]
What was the bug?

**Comment by ptersilie** [comment]
The issue you posted #136

**Comment by snim2** [comment]
Ah, cool! Will deal with the other PR first then this one next...

**Comment by snim2** [comment]
This fails a test on my machine, I think you forgot to commit a file:

``` python
______________________________________________________________________ Test_General.test_undo_bug ______________________________________________________________________

self = <test.test_eco.Test_General instance at 0x7fffef678440>

    def test_undo_bug(self):
        # Sometimes grammar changes can change subtrees that haven't been marked
        # as changed. As a consequence they are not marked with a version and
        # won't be reverted during an undo. This tests the fix in
        # incparser:reduce that version marks nodes whose parent has changed
        # during reparsing.
        grm = EcoFile("Undotest", "test/undobug1.eco", "Undo")
        t = TreeManager()
>       parser, lexer = grm.load()

test/test_eco.py:542: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
grammars/grammars.py:83: in load
    root, language, whitespaces = manager.load(self.filename)[0]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <jsonmanager.JsonManager object at 0x7fffef658a50>, filename = 'test/undobug1.eco'

    def load(self, filename):
        try:
            z = gzip.open(str(filename), "r")
            main = json.loads(z.read())
            z.close()
        except IOError:
            # backwards compatibility
>           fp = open(filename, "r")
E           IOError: [Errno 2] No such file or directory: 'test/undobug1.eco'

jsonmanager.py:52: IOError
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================ 1 failed, 10 passed, 8 skipped in 1.04 seconds ============================================================
```

**Comment by snim2** [comment]
Thanks!

**Pull request merged**
