### PR TITLE
Add JavaScript to sublang menu.

### PR DESCRIPTION
**Pull request by snim2**
This ensures that users can create a new JavaScript language box in a polyglot program.

### CODE REVIEW

**Comment by snim2** [comment]
This isn't quite ready to merge...

**Comment by snim2** [comment]
OK, I am able to test Ruby+JS integration now, so these commits fix the last few bugs:

jruby_js_working

**Comment by ltratt** [comment]
So is this ready for squashing and merging?

**Comment by snim2** [comment]
yes, it's ready to merge. Shall I squash?

**Comment by ltratt** [comment]
If you think appropriate, yes (it looks like it'll probably be a good idea to me, but it's up to you).

**Comment by ltratt** [comment]
Is this ready for merging?

**Comment by snim2** [comment]
Yes!

**Pull request merged**
