### PR TITLE
Added 'recent files' menu

### LINKED ISSUE #77: open recent files

### PR DESCRIPTION
**Pull request by ptersilie**
Fixes #77

### CODE REVIEW

**Comment by jaheba** [comment]
Newly created files are not added to the list.

**Comment by ptersilie** [comment]
Fixed newly created files and another bug

**Comment by jaheba** [comment]
Looks good for me.

**Comment by ptersilie** [comment]
This can be merged. The error will be fixed within the error recovery branch.

**Comment by ptersilie** [comment]
Let me quickly squash first.

**Pull request merged**
