### PR TITLE
Fixed retainability check

### PR DESCRIPTION
**Pull request by ptersilie**
A node can be retained if its content has the same textlength and the node
has the same position as before parsing. Previously we only checked
that the textlength matches. This commit adds the position check to
the retainability query.

### CODE REVIEW

**Comment by ltratt** [comment]
This looks good. Do you want to squash before I merge?

**Comment by ptersilie** [comment]
I wasn't planning to but don't mind it either. You could also use Github's squash and merge feature.

**Comment by ltratt** [comment]
[We don't use GH's squash feature: it's the PR author's job to squash (or not).]

I think you might want to quickly take a look and see if all three commits are meaningful in their own right. If you think they are, I'll merge as-is.

**Comment by ptersilie** [comment]
Ye I think they are meaningful on their own which is why I wasn't planning on merging them. But I'm also not opposed to it. Personally I would merge as is.

**Comment by ltratt** [comment]
Merge as-is it is!

**Pull request merged**
