### PR TITLE
Fix Java lexing rules for integers and floats

### LINKED ISSUE #209: Java lexing bug
This (correct) Java file doesn't lex / parse properly in Eco:

```java
class C {
    float f = 1.0F;
}
```

because of the `1.0F` part.

### PR DESCRIPTION
**Pull request by ptersilie**
Fixes #209

### CODE REVIEW

**Comment by ltratt** [comment]
[One build died, but for silly looking reasons. I've kicked it.]

**Comment by ltratt** [comment]
Hmm, both builds are saying `The command "tar xzf downloads/sip.tar.gz -C downloads --keep-newer-files" failed and exited with 2 during .`. Any thoughts?

**Comment by ptersilie** [comment]
Oh I think sourceforge is down again. :/ I'm still annoyed that we are dependent on that.

**Comment by ltratt** [comment]
Looks like it worked. Squash then I can merge?

**Comment by ptersilie** [comment]
Sure. After I squashed let me first check if the caching works.

**Comment by ltratt** [comment]
Did it work?

**Comment by ptersilie** [comment]
Not really. I added another commit to see if that keeps more files so that we don't have to build sip and pyqt each time the tests run.

**Comment by ptersilie** [comment]
Haha, the mirrorservice we were using for sourceforge is down as well now. :/

**Comment by ltratt** [comment]
The mirrorservice link works for me. I've tried kicking the build...

**Comment by ltratt** [comment]
OK, so the download did work. But now we have `tar` dying:

```
tar xzf downloads/sip.tar.gz -C downloads --keep-old-files
tar: sip-4.19.3/ChangeLog: Cannot open: File exists
tar: sip-4.19.3/configure.py: Cannot open: File exists
...
```

and so on.

I suggest we probably want to do something like:

```
test -f sip-4.19.3/ChangeLog || tar xzf downloads/sip.tar.gz -C downloads --keep-old-files
```

or just remove the `--keep-old-files`.

**Comment by ptersilie** [comment]
Oh I thought the `keep-old-files` would take care of the `File exists` by just "keeping the old files". What I want is to not overwrite the files again so `make` will not rebuild everything again. Is that what your `test` command does?

**Comment by ltratt** [comment]
What my suggestion does is not even run `tar` if (at least one of) the files exists.

**Comment by ptersilie** [comment]
Hmm, even though I'm caching the build folders now and not overwriting the files again tar, PyQt still rebuild every time travis runs, which takes 4x longer than the tests.

**Comment by ltratt** [comment]
You probably want to guard these lines:

```
     cd downloads/sip-4.19.3 && python configure.py && sudo make && sudo make install && cd ../../
     cd downloads/PyQt4_gpl_x11-4.12.1 && python configure.py --confirm-license && sudo make && sudo make install && cd ../../
```

since, I think, at the moment they're run even if we haven't downloaded anything. The configure script probably touches some files which then cause make to do stuff.

**Comment by ltratt** [comment]
Time to resurrect this one :)

**Comment by ptersilie** [comment]
I added some more guards to avoid unneccesary building which seems to work now. If you are happy with this I can squash and we can merge.

**Comment by ptersilie** [comment]
This reduced the test runtime from 18 to 3 minutes.

**Comment by ltratt** [comment]
> This reduced the test runtime from 18 to 3 minutes.

Eh?! Any idea why?

**Comment by ptersilie** [comment]
Because it doesn't need to rebuild PyQt each time which was really slow. The whole reason I did all those experiments.

**Comment by ltratt** [comment]
Aha, I see. So is this ready for squashing?

**Comment by ptersilie** [comment]
Yes, I can squash if you are happy.

**Comment by ltratt** [comment]
Yep, please squash.

**Comment by ptersilie** [comment]
Squashed!

**Review by ltratt — APPROVED** [review]

**Pull request merged**
