### PR TITLE
Fix JRuby exporter.

### PR DESCRIPTION
**Pull request by snim2**
For reasons known only to git, the JRuby exporter had some merge conflicts with the branch on the #141 PR. This PR fixes problems introduced by that merge conflict.

### CODE REVIEW

**Comment by ltratt** [comment]
Not that I mind this commit, but it doesn't seem to be anything to do with a merge conflict?

**Comment by snim2** [comment]
This PR changes `exporter/jruby.py` to match the version of that file you merged in #146 When #141 was merged, the file had been changed in that PR. I have no idea why bringing that branch up to date with master caused the JRuby file to change...

**Comment by ltratt** [comment]
Ah, I see. It's probably something to do one of the branches being a little more out of date, but in such a way that git could automatically resolve the differences, and thus not explicitly tell you that something had happened.

Once the test have passed, I'll merge.

**Comment by snim2** [comment]
Many thanks.

**Pull request merged**
