### PR TITLE
Hardcoded shortcuts for OS X

### PR DESCRIPTION
**Pull request by jaheba**

### CODE REVIEW

**Comment by ptersilie** [comment]
Is this the only shortcut for now?

**Comment by jaheba** [comment]
Yes, but there should be others. For example I think `ctrl+space` has to be
changed too.

**Comment by ptersilie** [comment]
As I am not using OSX, which shortcuts we need is completely up to you. :) Let me know when I should merge something.

**Comment by jaheba** [comment]
I looked through all short cuts we currently support. Those two are the only ones being different in OS X.

**Comment by ptersilie** [comment]
Good. Merged.

**Pull request merged**
